version: '3.8'

services:
  frontend:
    container_name: climate-frontend
    image: climateprediction.xyz:5000/climate-frontend
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - climate
    volumes:
      - type: volume
        source: climate
        target: /usr/climate
      - type: volume
        source: certbot_conf
        target: /etc/letsencrypt
      - type: volume
        source: certbot_www
        target: /var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    deploy:
      placement:
        constraints:
          - node.role == worker

  backend:
    container_name: climate-backend
    image: climateprediction.xyz:5000/climate-backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    networks:
      - climate
    volumes:
      - type: volume
        source: climate
        target: /usr/climate
    deploy:
      placement:
        constraints:
          - node.role == worker

  certbot:
    container_name: climate-certbot
    image: climateprediction.xyz:5000/certbot/certbot:v1.7.0
    volumes:
      - type: volume
        source: certbot_conf
        target: /etc/letsencrypt
      - type: volume
        source: certbot_www
        target: /var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    deploy:
      placement:
        constraints:
          - node.role == worker

networks:
  climate:
    driver: overlay

volumes:
  climate:
  certbot_conf:
    external: true
  certbot_www:
    external: true