version: '3.8'

services:
  frontend:
    container_name: climate-frontend
    image: climateprediction.xyz:5000/climate-frontend
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: bind
        source: /usr/climate
        target: /usr/climate
    secrets:
      - source: ssl_cert
        target: /etc/nginx/fullchain.pem
      - source: ssl_cert_key
        target: /etc/nginx/privkey.pem
      - source: ssl_conf
        target: /etc/nginx/options-ssl-nginx.conf
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    deploy:
      placement:
        constraints:
          - node.role == worker

  backend:
    container_name: climate-backend
    image: climateprediction.xyz:5000/climate-backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - type: bind
        source: /usr/climate
        target: /usr/climate
    deploy:
      placement:
        constraints:
          - node.role == worker

  certbot:
    container_name: climate-certbot
    image: certbot/certbot:v1.7.0
    volumes:
      - type: bind
        source: ./data/certbot/conf
        target: /etc/letsencrypt
      - type: bind
        source: ./data/certbot/www
        target: /var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  climate:
secrets:
  ssl_cert:
    file: ./data/certbot/conf/live/climateprediction.xyz/fullchain.pem
  ssl_cert_key:
    file: ./data/certbot/conf/live/climateprediction.xyz/privkey.pem
  ssl_conf:
    file: ./data/certbot/conf/options-ssl-nginx.conf