version: '3.8'

services:
  frontend:
    container_name: climate-frontend
    image: climateprediction.xyz:5000/climate-frontend
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/data/certbot/conf:/etc/letsencrypt
      - /var/data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - overnet
    deploy:
      placement:
        constraints:
          - node.role == worker

  backend:
    container_name: climate-backend
    image: climateprediction.xyz:5000/climate-backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - /var/data:/var/data
    networks:
      - overnet
    deploy:
      placement:
        constraints:
          - node.role == worker

networks:
  overnet:
    external: true