version: '3.8'

services:
  frontend:
    container_name: climate-frontend
    image: climateprediction.xyz:5000/climate-frontend
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: volume
        source: climate
        target: /usr/climate
      - type: bind
        source: /home/climate/data/certbot/conf
        target: /etc/letsencrypt
      - type: bind
        source: /home/climate/data/certbot/www
        target: /var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    deploy:
      placement:
        constraints:
          - node.role == worker

  backend:
    container_name: climate-backend
    image: climateprediction.xyz:5000/climate-backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - type: volume
        source: climate
        target: /usr/climate
    deploy:
      placement:
        constraints:
          - node.role == worker

  certbot:
    container_name: climate-certbot
    image: certbot/certbot:v1.7.0
    volumes:
      - type: bind
        source: /home/climate/data/certbot/conf
        target: /etc/letsencrypt
      - type: bind
        source: /home/climate/data/certbot/www
        target: /var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    deploy:
      placement:
        constraints:
          - node.role == worker

volumes:
  climate: