version: '3.8'

services:
  frontend:
    container_name: climate-frontend
    image: climateprediction.xyz:5000/climate-frontend
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/data/certbot/conf:/etc/letsencrypt
      - /var/data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - overnet
    deploy:
      placement:
        constraints:
          - node.role == worker

  backend:
    container_name: climate-backend
    image: climateprediction.xyz:5000/climate-backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - /var/data:/var/data
    networks:
      - overnet
    deploy:
      placement:
        constraints:
          - node.role == worker

  certbot:
    container_name: climate-certbot
    image: certbot/certbot:v1.7.0
    volumes:
      - /var/data/certbot/conf:/etc/letsencrypt
      - /var/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - overnet
    deploy:
      placement:
        constraints:
          - node.role == manager

  jenkins:
    container_name: climate-jenkins
    image: jenkins/jenkins:alpine3.19-jdk21
    command: "java -jar /usr/share/jenkins/jenkins.war"
    volumes:
      - /var/data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - overnet
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  overnet:
    driver: overlay
    driver_opts:
      encrypted: "true"