version: '3.8'

services:
  nginx:
    container_name: climate-jenkins-nginx
    image: nginx:1.24.0-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/data/certbot/conf:/etc/letsencrypt
      - /var/data/certbot/www:/var/www/certbot
      - ./nginx/jenkins.conf:/etc/nginx/conf.d/jenkins.conf
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - overnet
    deploy:
      placement:
        constraints:
          - node.role == manager

  certbot:
    container_name: climate-certbot
    image: certbot/certbot:v1.7.0
    volumes:
      - /var/data/certbot/conf:/etc/letsencrypt
      - /var/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - overnet
    deploy:
      placement:
        constraints:
          - node.role == manager

  jenkins:
    container_name: climate-jenkins
    image: climateprediction.xyz:5000/climate-jenkins
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    command: "java -jar /usr/share/jenkins/jenkins.war"
    volumes:
      - /var/data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - overnet
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  overnet:
    external: true